services:
  - type: web
    name: open-webui
    runtime: docker
    repo: https://github.com/open-webui/open-webui

databases:
  - name: webui-db
    plan: free
    databaseName: webui
    user: webui
    region: oregon
